version: '3.9'

services:
  # Main application service
  ohlcv-rag:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - ohlcv-rag:latest
    image: ohlcv-rag:${IMAGE_TAG:-latest}
    container_name: ohlcv-rag-app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_SOURCE=${DATA_SOURCE:-yahoo}
      - VECTOR_STORE_TYPE=${VECTOR_STORE_TYPE:-chromadb}
      - LLM_MODEL=${LLM_MODEL:-gpt-3.5-turbo}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DOCKER_BUILDKIT=1
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    networks:
      - ohlcv-network
    restart: unless-stopped
    command: ["python", "main_oop.py", "interactive"]

  # Development service with additional tools
  ohlcv-rag-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: ohlcv-rag:${IMAGE_TAG:-latest}-dev
    container_name: ohlcv-rag-dev
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_SOURCE=${DATA_SOURCE:-yahoo}
      - VECTOR_STORE_TYPE=${VECTOR_STORE_TYPE:-chromadb}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    volumes:
      - .:/app
      - ./data:/data
      - ./logs:/app/logs
    networks:
      - ohlcv-network
    ports:
      - "8888:8888"  # Jupyter
    stdin_open: true
    tty: true
    command: ["python", "main_oop.py", "interactive"]

  # ChromaDB service (default vector store)
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - chromadb-data:/chroma/chroma
    networks:
      - ohlcv-network
    ports:
      - "8000:8000"
    restart: unless-stopped
    profiles:
      - chromadb

  # Weaviate service (alternative vector store)
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - QUERY_DEFAULTS_LIMIT=25
      - DEFAULT_VECTORIZER_MODULE=none
    volumes:
      - weaviate-data:/var/lib/weaviate
    networks:
      - ohlcv-network
    ports:
      - "8080:8080"
    restart: unless-stopped
    profiles:
      - weaviate

  # Qdrant service (alternative vector store)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - ohlcv-network
    ports:
      - "6333:6333"
    restart: unless-stopped
    profiles:
      - qdrant

  # Milvus service (alternative vector store)
  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - milvus-etcd:/etcd
    networks:
      - ohlcv-network
    profiles:
      - milvus
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  milvus-minio:
    image: minio/minio:latest
    container_name: milvus-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - milvus-minio:/minio_data
    networks:
      - ohlcv-network
    profiles:
      - milvus
    command: minio server /minio_data

  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus
    environment:
      - ETCD_ENDPOINTS=milvus-etcd:2379
      - MINIO_ADDRESS=milvus-minio:9000
    volumes:
      - milvus-data:/var/lib/milvus
    networks:
      - ohlcv-network
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - milvus-etcd
      - milvus-minio
    profiles:
      - milvus

networks:
  ohlcv-network:
    driver: bridge

volumes:
  chromadb-data:
  weaviate-data:
  qdrant-data:
  milvus-data:
  milvus-etcd:
  milvus-minio: